# Generated by Django 3.0.8 on 2020-09-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_user2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User2',
            new_name='User1s',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='User2s',
        ),
    ]
