# Generated by Django 3.0.8 on 2020-09-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_userprofileinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Questions'},
        ),
    ]
