# Generated by Django 3.0.8 on 2020-09-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20200917_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Questions(Pytania)'},
        ),
    ]
